package jolyjdia.utils;

import com.mojang.authlib.GameProfile;
import com.mojang.authlib.properties.Property;
import com.mojang.authlib.properties.PropertyMap;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.SkullMeta;
import org.jetbrains.annotations.NotNull;

import java.lang.reflect.Field;
import java.util.UUID;

public enum Head {
    DEVIL("OWRhMzkyNjllZjQ1ZjgyNWVjNjFiYjRmOGFhMDliZDNjZjA3OTk2ZmI2ZmFjMzM4YTZlOTFkNjY5OWFlNDI1In19fQ=="),
    ANGEL("N2VjMjM0NjdiOTMwNWE5MmFlOGQ1ODE2ZDNmZmUxMmIyOWViZDU0ZTZkYTY3Y2M0ZGE1M2IxNDA3OTJkODhmIn19fQ=="),
    GHOST_REDEYE("ZGQ1NGRhM2JjMGE5MzdkZGY2MjVlMzM5YjdlMzJhNGIwMjM5NGUzMWQyY2JkODFmYzFjMWYyNWIyNTdmNjkifX19"),
    GHOST("NjhkMjE4MzY0MDIxOGFiMzMwYWM1NmQyYWFiN2UyOWE5NzkwYTU0NWY2OTE2MTllMzg1NzhlYTRhNjlhZTBiNiJ9fX0="),
    NOTCH("YTExNmU2OWE4NDVlMjI3ZjdjYTFmZGRlOGMzNTdjOGM4MjFlYmQ0YmE2MTkzODJlYTRhMWY4N2Q0YWU5NCJ9fX0="),
    NOTCH_SUNGLASSES("ZTc1NGUyOGI3ZWI4NGU0NGVlODYzNDdiMjJjZjYyNDFmOWIyNjMzOGE2NTZhZGZkMjhkNjM3MDYzNTk3MDU3In19fQ=="),
    SANTA("MmQ2MWNjYmZkY2RmODk0MWFkYWY3NmM2YzBlMDE4MmQyYzhiYmI1ZGMxOGYzNzQ4OTU2NTJiYzY2MWI2ZWQifX19"),
    ASTRONAUT("OTVlM2U3ODUxMjc0OGJhODUzYTgyMGNiNTY3MTZmNzhmYWFjMTYxZTQzYzYxZDkyNDFiYTU0OWNlNzQwZDVjZiJ9fX0="),
    WITCH("MWE2NDEwMzc4OTMwZDhiMTQxMjdkNDM4OGRlNzQ2MzZkMzRlZTI1MTdmM2IxZjJjYjZjZTYyYTFlNzIxNTMifX19"),
    HALO_GAME("NWJiMjhiYjBiZjFhZDIxN2QyYTgxMTkxZWZmY2M2OWZlMTc0NzE0YTQzMmZkNzFmYTYwYWE1MGYzNzEyYjk3In19fQ=="),
    CUPIDON("NzBkODA2ZjE5YTc1MjZmYzZmYTQ4ZjQyZjcwM2I5MGFkZDgxNDJkYWM3ZjM3YWQxYmUxYjRlZGNhYzViYTgzIn19fQ=="),
    HEROBRINE("Y2M3ZGYwYmJkY2U0YmYzYjQ1MjY4MWViNDcxZDExMDM2NWIyNDY4ZjFlNzIwNzA0YTIwMzczNGJkODQ4MzczIn19fQ=="),
    CLASSIC_HEROBRINE("OThiN2NhM2M3ZDMxNGE2MWFiZWQ4ZmMxOGQ3OTdmYzMwYjZlZmM4NDQ1NDI1YzRlMjUwOTk3ZTUyZTZjYiJ9fX0="),
    IRON_GOLEM("ODkwOTFkNzllYTBmNTllZjdlZjk0ZDdiYmE2ZTVmMTdmMmY3ZDQ1NzJjNDRmOTBmNzZjNDgxOWE3MTQifX19"),
    ENDERMAN("N2E1OWJiMGE3YTMyOTY1YjNkOTBkOGVhZmE4OTlkMTgzNWY0MjQ1MDllYWRkNGU2YjcwOWFkYTUwYjljZiJ9fX0="),
    GOLEM("NWUyNGViYWUzOWEyNDM4ZmRkYTc1NzBhNTVlYjNmMDQyOGU5Zjg0Yzc3NDkzNTQyZmEzZTE0MzdkMjRiOWUifX19"),
    MINER("ZDM1NzQ0NGFkZTY0ZWM2Y2VhNjQ1ZWM1N2U3NzU4NjRkNjdjNWZhNjIyOTk3ODZlMDM3OTkzMTdlZTRhZCJ9fX0="),
    DIAMOND_ORE("NmFjMTQyM2VmNzhhNDBhNzhlMzY4ZjFiOTFmNjMzNzZiOTQzMjAyOTlhZTM5MTc3MTU2NWEzZjQ2NWI1OTcifX19"),
    ELFMAN_1("OTU3YmU0N2JlNmY0YjI2YjA3OWM3NzU4YjY2Y2E4ODhiOWMzNGVhZWQ3MmU2ZTU4YjEzZDg3ZmZkYTBiMyJ9fX0="),
    ELFMAN_2("NTVhZmQ3Y2FjMzY1Mzk4YjE1YjAzNDlkNDkyZmNmZWQwYjdjZDE5NTZlNGUzNGQzYmQ1MTNkZjgxMTJiIn19fQ=="),
    ELFMAN_3("YWI2ZTllMTNjOWQ2Y2UxZjljYzBjMmJhOThjNTA2ZDUxNzNhZmNkOTkzOTk2YzgxNjhkNjFjNzliMDQzY2IifX19"),
    ELFMAN_4("MmI2MDgxYWFjZmQzNDdjMTI2YWI0ZTkwOTA5ZmRkMzdhNGRlYjVjYTE5MTg0ZWI0Yzk1OTE3MzRmODU4NjgifX19"),
    ELFMAN_5("N2ZiYmY5ZTRlZmQwMTkzYzUyNjQ3MTliYTQ3OGI5MTdhMjYwNzE0NmY2ZWE4MGNiNWZlMDkzYzNiOTlhNGMifX19"),
    ELFGIRL_1("MzE5YzM1NjY2M2NmNTYyNjM3NDg3NDZjNjI0NjIwNzllMDJiN2IyZWVmOTVhZGVkMDY5ZmFhY2M1NGIzMTI5In19fQ=="),
    ELFGIRL_2("ZDg4YWRiMjIxYzZlYTRmNGU4YWRiYTc2ZWY4NGMyODExYTYwODQ0YjQzMTNmYzkyM2QxMzU5YmNlNTE3MTRjYSJ9fX0="),
    ELFGIRL_3("ZmM2ZTc5ZDE3MTc5MDJmNzFkYzU1M2M1MzczZmYyZTE3YmFlNjE5YjM5ZjhkZGJkZDIzMzgzZGQ1NWIzOTYifX19"),
    BLUE_PRESENT("MWI2NzMwZGU3ZTViOTQxZWZjNmU4Y2JhZjU3NTVmOTQyMWEyMGRlODcxNzU5NjgyY2Q4ODhjYzRhODEyODIifX19"),
    AQUA_PRESENT("NTEyZTk0NTFjZGIxOTZiNzgxOTVhOGYwYTRiOWMxYzBhMDRmNTgyNzg4NzkyN2I2YTgyYWFkMzljYWIyZjQzMCJ9fX0="),
    GOLD_PRESENT("NmI0Y2RlMTZhNDAxNGRlMGE3NjUxZjYwNjdmMTI2OTViYjVmZWQ2ZmVhZWMxZTk0MTNjYTQyNzFlN2M4MTkifX19"),
    GREEN_PRESENT("OTcxNWY1MzdmZTdhZjZmNWFhNmViOThhZDY5MDJjMTNkMDVmYjM2YzE2YjMxMWVkODMyYjA5YjU5ODgyOCJ9fX0="),
    DARK_ORANGE_PRESENT("OTI4ZTY5MmQ4NmUyMjQ0OTc5MTVhMzk1ODNkYmUzOGVkZmZkMzljYmJhNDU3Y2M5NWE3YWMzZWEyNWQ0NDUifX19"),
    PURPLE_PRESENT("ODdmY2FlNTgxY2Q2N2U2MTJkMzU1YzExNGI2YjgxODk0MjM2MGQwM2U0YTFiYTJiYzYxYjgxYTdlMTA3MjYyIn19fQ=="),
    RED_PRESENT("NmNlZjlhYTE0ZTg4NDc3M2VhYzEzNGE0ZWU4OTcyMDYzZjQ2NmRlNjc4MzYzY2Y3YjFhMjFhODViNyJ9fX0="),
    DARK_PINK_PRESENT("NDdlNTVmY2M4MDlhMmFjMTg2MWRhMmE2N2Y3ZjMxYmQ3MjM3ODg3ZDE2MmVjYTFlZGE1MjZhNzUxMmE2NDkxMCJ9fX0="),
    TURQUOISE_PRESENT("N2ZjZDFjODJlMmZiM2ZhMzY4Y2ZhOWE1MDZhYjZjOTg2NDc1OTVkMjE1ZDY0NzFhZDQ3Y2NlMjk2ODVhZiJ9fX0="),
    INDIGO_PRESENT("NGFjYjNjMWUxYjM0Zjg3MzRhZWRmYWJkMWUxZjVlMGIyODBiZWY5MjRmYjhiYmYzZTY5MmQyNTM4MjY2ZjQifX19"),
    ORANGE_PRESENT("ZWUzYThmZDA4NTI5Nzc0NDRkOWZkNzc5N2NhYzA3YjhkMzk0OGFkZGM0M2YwYmI1Y2UyNWFlNzJkOTVkYyJ9fX0="),
    LIGHT_BLUE_PRESENT("ODRlMWM0MmYxMTM4M2I5ZGM4ZTY3ZjI4NDZmYTMxMWIxNjMyMGYyYzJlYzdlMTc1NTM4ZGJmZjFkZDk0YmI3In19fQ=="),
    BLACK_PRESENT("NWM3MTJiMTk3MWM1ZjQyZWVmZjgwNTUxMTc5MjIwYzA4YjgyMTNlYWNiZTZiYzE5ZDIzOGMxM2Y4NmUyYzAifX19"),
    PINK_PRESENT("MTBjNzVhMDViMzQ0ZWEwNDM4NjM5NzRjMTgwYmE4MTdhZWE2ODY3OGNiZWE1ZTRiYTM5NWY3NGQ0ODAzZDFkIn19fQ=="),
    CHAGRIN("ZTlkZDNhZGRiZjc1MzE1YzY0ZWZhODM0ODkxYjY4N2U3Zjk0NWI2N2I1NmJlZWRmMTgxZGJjYmRlNTlhMWQifX19"),
    CRY("MWYxYjg3NWRlNDljNTg3ZTNiNDAyM2NlMjRkNDcyZmYyNzU4M2ExZjA1NGYzN2U3M2ExMTU0YjViNTQ5OCJ9fX0="),
    DERP("M2JhYWJlNzI0ZWFlNTljNWQxM2Y0NDJjN2RjNWQyYjFjNmI3MGMyZjgzMzY0YTQ4OGNlNTk3M2FlODBiNGMzIn19fQ=="),
    GRIMACE("N2ZmYWNjZjE3ODc5YjE3ODkxZmM1ZWY2NjQ3MmNjMDY2YTg1YmZhMzFiNmQ3ODZjMzJhZmVlNDc5NjA2OGQifX19"),
    HAPPY("NTA1OWQ1OWViNGU1OWMzMWVlY2Y5ZWNlMmY5Y2YzOTM0ZTQ1YzBlYzQ3NmZjODZiZmFlZjhlYTkxM2VhNzEwIn19fQ=="),
    KISS("NTQ1YmQxOGEyYWFmNDY5ZmFkNzJlNTJjZGU2Y2ZiMDJiZmJhYTViZmVkMmE4MTUxMjc3Zjc3OWViY2RjZWMxIn19fQ=="),
    OHMYGOD("YmMyYjliOWFlNjIyYmQ2OGFkZmY3MTgwZjgyMDZlYzQ0OTRhYmJmYTEzMGU5NGE1ODRlYzY5MmU4OTg0YWIyIn19fQ=="),
    SURPRISED("ZjcyMGRmOTExYzA1MjM3NzA2NTQwOGRiNzhhMjVjNjc4Zjc5MWViOTQ0YzA2MzkzNWFlODZkYmU1MWM3MWIifX19"),
    TIRED("NjRkNzdlOTY0Y2ZmYmFkMTliMWVkOTYwZjA0YjFjMmVlZDNiYjc2ODcwMTYyZTczY2RmNjgzOGVjNjM2MTIifX19"),
    WINK("ZjRlYTJkNmY5MzlmZWZlZmY1ZDEyMmU2M2RkMjZmYThhNDI3ZGY5MGIyOTI4YmMxZmE4OWE4MjUyYTdlIn19fQ=="),
    ANXIOUS("ZjcyMGRmOTExYzA1MjM3NzA2NTQwOGRiNzhhMjVjNjc4Zjc5MWViOTQ0YzA2MzkzNWFlODZkYmU1MWM3MWIifX19"),
    DEAL_WITH_IT("ODY4ZjRjZWY5NDlmMzJlMzNlYzVhZTg0NWY5YzU2OTgzY2JlMTMzNzVhNGRlYzQ2ZTViYmZiN2RjYjYifX19"),
    HOT("ZDU3MGE5MmY3MDkwMjIzMjcwMjg4ZmFhNWM5YWRiNTNlODY4NjFiOWYyZjNkOWY5MDk1NDAxNTM1MDcyYjMifX19"),
    IMPRESSED("YmMyYjliOWFlNjIyYmQ2OGFkZmY3MTgwZjgyMDZlYzQ0OTRhYmJmYTEzMGU5NGE1ODRlYzY5MmU4OTg0YWIyIn19fQ=="),
    IN_LOVE("MTI5ZmI5ZjU5M2I2YWU1MzNkZmE4Y2U3OTYxNWZjYzM1ODk0YTQyY2JiNDFkZTU5OGQ2OTQ3NjczNTJmZSJ9fX0="),
    MUSTACHE("MzYzNmYyNzI0YWE2YWE0ZGU3YWM0NmMxOWYzYzg0NWZiMTQ4NDdhNTE4YzhmN2UwM2Q3OTJjODJlZmZiMSJ9fX0="),
    RIP("YjM3MWU0ZTFjZjZhMWEzNmZkYWUyNzEzN2ZkOWI4NzQ4ZTYxNjkyOTk5MjVmOWFmMmJlMzAxZTU0Mjk4YzczIn19fQ=="),
    SLUMBER("NTJlOTgxNjVkZWVmNGVkNjIxOTUzOTIxYzFlZjgxN2RjNjM4YWY3MWMxOTM0YTQyODdiNjlkN2EzMWY2YjgifX19"),
    TALKATIVE("NjM2ZTI2YzQ0NjU5ZTgxNDhlZDU4YWE3OWU0ZDYwZGI1OTVmNDI2NDQyMTE2ZjgxYjU0MTVjMjQ0NmVkOCJ9fX0="),
    GOLD_CHEST("NDUyY2VlZDA2NDgzNWVhMjMyZTY1NmE3M2Y4MmVkNzYxODI3ODU5YzkxMzQ0OTMxNGI4ZmQyMWIzZDExZDYifX19"),
    DIAMOND_CHEST("M2FkYmNmYjI4ODIxNWE4ZDE1M2RkZmRkYjM2YmQyZWQ3YTM3YWRkMzU2NjJmODYzM2Y3MTFkMmRmY2ViNDE3YyJ9fX0="),
    IMPERIAL_CHEST("OWM5NmJlNzg4NmViN2RmNzU1MjVhMzYzZTVmNTQ5NjI2YzIxMzg4ZjBmZGE5ODhhNmU4YmY0ODdhNTMifX19"),
    RUBY_CHEST("ZWE5YjMwYTA4NzRlNTc2YzNlOGI1YzllNmI0MmMwZDA4ODQ1ZTUxNWY3N2M0ZWQ0YmVlYWJkYWI3NjkyIn19fQ=="),
    GRAY_CHEST("ZTFkYWVlM2Y0NTNhMzhlMzVkOGNhYjgzNTNjNWQyOGNjZTFiNjc1ZmY5NGI5MmU1YzRhZjJkNjQ1MjAzMWEwIn19fQ=="),
    ARROW_LEFT("ODY5NzFkZDg4MWRiYWY0ZmQ2YmNhYTkzNjE0NDkzYzYxMmY4Njk2NDFlZDU5ZDFjOTM2M2EzNjY2YTVmYTYifX19"),
    ARROW_RIGHT("ZjMyY2E2NjA1NmI3Mjg2M2U5OGY3ZjMyYmQ3ZDk0YzdhMGQ3OTZhZjY5MWM5YWMzYTkxMzYzMzEzNTIyODhmOSJ9fX0="),
    BODY_GUARD("ZGQ5OWUyNmUyYWZiYjhhYjIyM2Y3MjZmNTJmMTI0ZTMxMTc0YjA3MjJkNTI5ZGNmNzZjMmIyZjIyMGU0NDQxMiJ9fX0="),
    YOUTUBE("Mzc1NjUxYTk0OGFhMjAzMGEyZDViNmMyZmJkZTVkNThjNGI4YTBjOGMzZjllNGMzNjBmM2Y3MmUyOTJlNTExMyJ9fX0="),
    GOLD("NGFkMDQ3NmU4NjcxNjk2YWYzYTg5NDlhZmEyYTgxNGI5YmRkZTY1ZWNjZDFhOGI1OTNhZWVmZjVhMDMxOGQifX19"),
    RAINBOW("N2JlNzU0NTI5N2RmZDYyNjZiYmFhMjA1MTgyNWU4ODc5Y2JmYTQyYzdlN2UyNGU1MDc5NmYyN2NhNmExOCJ9fX0="),
    RED_ORE("NWNkMzRjNzIxYjY1OTQwOTlhZmNmNDFhODJmNjQ4MTc2Yzk0YWIzMmRlOTRmZjMwZDExM2NkYmY4M2RjOGIifX19"),
    GREEN_ORE("ZGM2YmFjZDM2ZWQ2MGY1MzMxMzhlNzU5YzQyNTk0NjIyMmI3OGVkYTZiNjE2MjE2ZjZkY2MwOGU5MGQzM2UifX19"),
    GREEN_REDSTONE("YTdiN2E5MzA4NmJhMzFhZWQyMzI5MzE0NTJlODQ1NDlhYmNkZmIxYjcxNTdmYTQ1ZDRjMjk1OTFlMTdmMTlkNSJ9fX0="),
    RED_REDSTONE("YmI3OGZhNWRlZmU3MmRlYmNkOWM3NmFiOWY0ZTExNDI1MDQ3OWJiOWI0NGY0Mjg4N2JiZjZmNzM4NjEyYiJ9fX0="),
    EARTH("MmUyY2M0MjAxNWU2Njc4ZjhmZDQ5Y2NjMDFmYmY3ODdmMWJhMmMzMmJjZjU1OWEwMTUzMzJmYzVkYjUwIn19fQ=="),
    CAULDRON("Zjk1NWJkNTExNjM1YTc3ZTYxNmEyNDExMmM5ZmM0NTdiMjdjOGExNDZhNWU2ZGU3MjdmMTdlOTg5ODgyIn19fQ=="),
    PLUS("OWEyZDg5MWM2YWU5ZjZiYWEwNDBkNzM2YWI4NGQ0ODM0NGJiNmI3MGQ3ZjFhMjgwZGQxMmNiYWM0ZDc3NyJ9fX0="),
    MINUS("OTM1ZTRlMjZlYWZjMTFiNTJjMTE2NjhlMWQ2NjM0ZTdkMWQwZDIxYzQxMWNiMDg1ZjkzOTQyNjhlYjRjZGZiYSJ9fX0=");

    private final String texture;

    Head(String s) {
        this.texture = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv" + s;
    }

    public String getTexture() {
        return this.texture;
    }
    @NotNull
    public static ItemStack getSkull(String var0) {
        ItemStack var1 = new ItemStack(Material.PLAYER_HEAD);
        SkullMeta var2 = (SkullMeta)var1.getItemMeta();
        GameProfile var3 = new GameProfile(UUID.randomUUID(), null);
        PropertyMap var4 = var3.getProperties();
        var4.put("textures", new Property("textures", var0));

        try {
            assert var2 != null;
            Field var5 = var2.getClass().getDeclaredField("profile");
            var5.setAccessible(true);
            var5.set(var2, var3);
        } catch (IllegalAccessException | NoSuchFieldException var6) {
            var6.printStackTrace();
        }

        var1.setItemMeta(var2);
        return var1;
    }
}
